### ISSUE TITLE
Clear cells in demo notebook?

### ISSUE THREAD

**Issue by psychemedia** [binder-examples/jupyter-rise#1]
The ability to generate the plot outputs live may be more compelling if cells in the demo notebook were cleared so the user had to generate them?

Or is the point that the output can be pre-prepared and then updated?

Maybe need a quick demo of each way of working?

**Comment by choldgraf** [comment]
This is a bit tricky IME, because RISE doesn't always handle the vertical scroll of a slide well when the output of the slide is fairly large. If the output is already there, it "just works" which is why I included it. That said, I agree that it'd be good if users could create the slide outputs...

**Comment by willingc** [comment]
@psychemedia If you clear the notebook before saving in the repo, I think the output will not be generated until each cell is executed again. @damianavila, is that true for RISE?

**Comment by choldgraf** [comment]
@willingc yep! That is true for RISE as well. The challenge is that sometimes RISE doesn't handle vertical space very elegantly. If you launch RISE when the output is already there, then it knows to allow for enough vertical space in the page so you can scroll down to see it. If you don't have the output already there, then sometimes after running the cell to produce the output, it gets cut off on the bottom and you can't scroll down.

**Comment by psychemedia** [comment]
@choldgraf " If you don't have the output already there, then sometimes after running the cell to produce the output, it gets cut off on the bottom and you can't scroll down." 

Yes, I'd noticed that. One of the downsides of pre-populating the cell when doing a live demo is that folk don't necessarily appreciate that the content can be generated by actually running the cell?

**Comment by damianavila** [comment]
@choldgraf or @psychemedia can you open an issue about this in the RISE repo? We should be able to fix it. We just need to make the output observer intelligent enough to set the scrolling if necessary.

**Comment by damianavila** [comment]
> We just need to make the output observer intelligent enough to set the scrolling if necessary.

I think I have fixed it...

![observer_scroll](https://user-images.githubusercontent.com/1640669/33522263-3a83ceea-d7c7-11e7-96a2-a0e3588e9aa4.gif)

**Comment by choldgraf** [comment]
wow! nicely done @damianavila !!! Is this in RISE master now?

**Comment by damianavila** [comment]
Not yet! Just changes on the fly, but will try to put it on master today/tomorrow.

**Comment by choldgraf** [comment]
sweet! I'll source this off of master when that happens and see if that fixes it :-)

**Comment by willingc** [comment]
@damianavila This is lovely. I would include the GIF in your docs too :tada:

**Comment by damianavila** [comment]
> I would include the GIF in your docs too

Do you have any suggestion where to put it?

**Comment by choldgraf** [comment]
@damianavila could just go on the landing page of the docs + the README.md page somewhere as a demo...it's a nice way to highlight the functionality of RISE

**Comment by damianavila** [comment]
Thanks for the suggestion! @choldgraf and @willingc

**Comment by damianavila** [comment]
> Thanks for the suggestion! @choldgraf and @willingc

Done!
Added to docs and README, thanks again for the idea.

**Comment by willingc** [comment]
For others finding this in the future, the RISE documentation is found [here](https://damianavila.github.io/RISE/). Thanks all.

**Comment by yuvipanda** [comment]
Has there been a new release of RISE? If so we can update repo2docker, and then clear out outputs from here :)

Yay for @damianavila :)

**Comment by willingc** [comment]
I'm going to go ahead and close this issue since changes will land in RISE master soon. Thanks @damianavila, @choldgraf, and @psychemedia.

**Comment by willingc** [comment]
Soon @yuvipanda ;-)

**Comment by choldgraf** [comment]
yep, that PR is close. not sure when @damianavila is planning on cutting a release but perhaps if we all told him how awesome he was it would help nudge him in that direction :-D

**Comment by damianavila** [comment]
>  if we all told him how awesome he was it would help nudge him in that direction :-D

Jaja... took some time but finally 5.2.0 (including this fix) is out!

**Comment by choldgraf** [comment]
sweet! I updated https://github.com/binder-examples/jupyter-rise to use this, and cleared the outputs of the notebook so that this use-case is clearer :-)

thanks @damianavila !!!
